version: '3'
services:
  caddy:
    image: caddy:2.7.5
    restart: always
    volumes:
      # static sites
      - ./www/veet:/var/www/veet
      # configuration
      - ./.caddy_data:/data
      - ./.caddy_config:/config
      - ./conf/basic_auth.conf:/etc/basic_auth.conf
      - ./conf/caddyfile_optional.conf:/etc/caddyfile_optional.conf
      - ./caddy/etc/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/etc/tls_auto:/etc/tls_auto
      - ./mail-acme-challenge:/mail-acme-challenge
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./conf/caddy/.env
      - ./conf/caddy/sensitive.env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  veet-api:
    image: veet-api:latest
    restart: always
      - ./conf/api-veet.env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

volumes:
  docs-db-data: